name: Deploy to cPanel using ChatGPT

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install --save --legacy-peer-deps  react-tilt

      - name: Build app
        run: npm run build

      - name: Create tarball
        run: tar -czf app.tar.gz dist/

      - name: Copy files to cPanel
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USER }}
          password: ${{ secrets.CPANEL_PASS }}
          source: app.tar.gz
          target: /home/dvlprkrishna/public_html/

      - name: Extract tarball
        run: ssh dvlprkrishna@krishnasahu.in 'cd public_html/ && tar -xzf app.tar.gz'

      - name: Restart web server
        run: ssh dvlprkrishna@krishnasahu.in 'sudo systemctl restart apache2'
